<?php

return array(
        UserRole::ADMIN => array(
                                'name'=>'Admin',
                                'routes'=>array('cloak'=>'get', 
                                                'admin-management'=>'get',
                                                'admin-management/add-admin'=>'post',
                                                'admin-management/edit-admin'=>'post',
                                                'admin-management/delete-admin'=>'post',
                                                'company-management'=>'get',
                                                'company-management/{companyId}'=>'get',
                                                'company-management/add-enterprise-company'=>'post',
                                                'company-management/edit-company'=>'post',
                                                'company-management/delete-company'=>'post',
                                                'company-management/company-projects'=>'post',
                                                'company-management/company-divisions'=>'post',
                                                'company-management/division-business-units'=>'post',
                                                'company-management/business-unit-groups'=>'post',
                                                'company-management/add-division'=>'post',
                                                'company-management/edit-division'=>'post',
                                                'company-management/delete-division'=>'post',
                                                'company-management/add-business-unit'=>'post',
                                                'company-management/edit-business-unit'=>'post',
                                                'company-management/delete-business-unit'=>'post',
                                                'company-management/add-group'=>'post',
                                                'company-management/edit-group'=>'post',
                                                'company-management/delete-group'=>'post',
                                                'company-management/add-helpline'=>'post',
                                                'company-management/delete-helpline'=>'post',
                                    
                                                'company-management/stats/{groupId}/{refDate}/{timeframe}'=>'get',
                                                'company-management/stats/{groupId?}/{refDate?}/{timeframe?}'=>'get',
                                                'company-management/stats/export/{groupId}/{refDate}/{timeframe}'=>'get',
                                                'company-management/stats/mail/{groupId}/{refDate}/{timeframe}'=>'post',
                                    
                                                'daily-signin/{groupId}/{signDate}'=>'get',
                                                'daily-signin/{groupId?}/{signDate?}'=>'get',
                                                'daily-signin/export/{groupId}/{signDate}'=>'get',
                                                'daily-signin/mail/{groupId}/{signDate}'=>'post',
                                                
                                    
                                                'worker-management'=>'get',
                                                'worker-management/add-worker'=>'post',
                                                'worker-management/get-worker-details/{authToken}'=>'get',
                                                'worker-management/edit-worker'=>'post',
                                                'worker-management/disable-worker'=>'post',
                                                'worker-management/delete-worker'=>'post',
                                                'worker-management/enable-worker'=>'post',
                                    
                                    
                                                'vehicle-management'=>'get',
                                                'vehicle-management/add-vehicle'=>'post',
                                                'vehicle-management/get-vehicle-details/{vehicleId}'=>'get',
                                                'vehicle-management/edit-vehicle'=>'post',
                                                'vehicle-management/delete-vehicle'=>'post',
                                                'vehicle-management/view/{vehicleId}/{inspectionId}'=>'get',
                                                'vehicle-management/view/{vehicleId}/{inspectionId?}'=>'get',
                                                'vehicle-management/export/{vehicleId}/{inspectionId}'=>'get',
                                                'vehicle-management/export/{vehicleId}/{inspectionId?}'=>'get',
                                                'vehicle-management/mail'=>'post',
                                                'vehicle-management/add-action'=>'post',
                                                'vehicle-management/get-inspection-details/{inspectionId}'=>'get',
                                                'vehicle-management/delete-vehicle'=>'post',
                                                
                                                'near-misses'=>'get',
                                                'near-misses/view/{nearMissId}'=>'get',
                                                'near-misses/export/{nearMissId}'=>'get',
                                                'near-misses/mail'=>'post',
                                                'near-misses/add-action'=>'post',
                                                'near-misses/delete-near-miss'=>'post',
                                                'near-misses/edit-near-miss'=>'post',
                                    
                                                'hazard-cards'=>'get',
                                                'hazard-cards/view/{hazardId}'=>'get',
                                                'hazard-cards/export/{hazardId}'=>'get',
                                                'hazard-cards/mail'=>'post',
                                                'hazard-cards/add-action'=>'post',
                                                'hazard-cards/delete-hazard-card'=>'post',
                                                'hazard-cards/edit-hazard-card'=>'post',
                                    
                                                'field-observations'=>'get',
                                                'field-observations/view/{positiveObservationId}'=>'get',
                                                'field-observations/export/{positiveObservationId}'=>'get',
                                                'field-observations/mail'=>'post',
                                                'field-observations/add-action'=>'post',
                                                'field-observations/delete-observation'=>'post',
                                                'field-observations/edit-observation'=>'post',
                                    
                                                'journeys'=>'get',
                                                'journey-management/view/{journeyId}'=>'get',
                                                'journey-management/view/{journeyId?}'=>'get',
                                                'journey-management/delete-journey'=>'post',
                                                
                                                'flha'=>'get',
                                                'flha/view/{flhaId}'=>'get',
                                                'flha/export/{flhaId}'=>'get',
                                                'flha/mail'=>'post',
                                                'flha/get-visitor-details/{visitorId}'=>'get',
                                                'flha/get-worker-details/{workerId}'=>'get',
                                                'flha/get-spotcheck-details/{spotcheckId}'=>'get',
                                                'flha/delete-flha'=>'post',
                                                'flha/edit-flha'=>'post',
                                                
                                                'faq'=>'get',
                                                'faq/manage'=>'get',
                                                'faq/add'=>'post',
                                                'faq/edit'=>'post',
                                                'faq/delete'=>'post',
                                    
                                                'tailgates'=>'get',
                                                'tailgates/view/{tailgateId}'=>'get',
                                                'tailgates/export/{tailgateId}'=>'get',
                                                'tailgates/mail'=>'post',
                                                'tailgates/get-visitor-details/{visitorId}'=>'get',
                                                'tailgates/get-worker-details/{workerId}'=>'get',
                                                'tailgates/delete-tailgate'=>'post',
                                                'tailgates/edit-tailgate'=>'post',
                                    
                                                'incident-cards'=>'get',
                                                'incident-cards/view/{incidentId}'=>'get',
                                                'incident-cards/export/{incidentId}'=>'get',
                                                'incident-cards/get-person-details/{personId}'=>'get',
                                                'incident-cards/mail'=>'post',
                                                'incident-cards/add-action'=>'post',
                                                'incident-cards/delete-incident'=>'post',
                                                'incident-cards/edit-incident'=>'post',
                                    
                                                'cards/review' => 'post',
                                                'profile'      => 'post',
                                                'profile/disable-tutorial' => 'get',

                                                'tickets'=>'get',
                                                'tickets/create-ticket-view' => 'get',
                                                'tickets/view/{ticketId}'=>'get',
                                                'tickets/create' => 'post',
                                                'tickets/delete' => 'post',
                                                'tickets/mail'=>'post',
                                                'tickets/update'=>'post',
                                                'tickets/export/{ticketId}' => 'get',

                                                'safety-manual' => 'get',
                                                'safety-manual/revisions' => 'get',
                                                'safety-manual/section/{sectionid}' => 'get',
                                                'safety-manual/mail'=>'post',
                                                'safety-manual/edit-safety-manual' => 'post',
                                                '/safety-manual/upload-image' => 'post',
                                                'safety-manual/export/{sectionId?}/{subsectionId?}' => 'get',
                                                'safety-manual/mail/{sectionId?}/{subsectionId?}' => 'get'
                                    )
                               ),
        UserRole::COMPANY_ADMIN => array(
                                'name'=>'Company Admin',
                                'routes'=>array(
                                                'admin-management'=>'get',
                                                'admin-management/add-admin'=>'post',
                                                'admin-management/edit-admin'=>'post',
                                                'admin-management/delete-admin'=>'post',
                                                'company-management'=>'get',
                                                'company-management/company-projects'=>'post',
                                                'company-management/company-divisions'=>'post',
                                                'company-management/division-business-units'=>'post',
                                                'company-management/business-unit-groups'=>'post',
                                                'company-management/add-division'=>'post',
                                                'company-management/edit-division'=>'post',
                                                'company-management/delete-division'=>'post',
                                                'company-management/add-business-unit'=>'post',
                                                'company-management/edit-business-unit'=>'post',
                                                'company-management/delete-business-unit'=>'post',
                                                'company-management/add-group'=>'post',
                                                'company-management/edit-group'=>'post',
                                                'company-management/delete-group'=>'post',
                                                'company-management/add-helpline'=>'post',
                                                'company-management/delete-helpline'=>'post',
                                                'upload-company-logo' => 'get|post',
                                                'company-logo' => 'get',
                                    
                                                'company-management/stats/{groupId}/{refDate}/{timeframe}'=>'get',
                                                'company-management/stats/{groupId?}/{refDate?}/{timeframe?}'=>'get',
                                                'company-management/stats/export/{groupId}/{refDate}/{timeframe}'=>'get',
                                                'company-management/stats/mail/{groupId}/{refDate}/{timeframe}'=>'post',
                                               
                                                'daily-signin/{groupId}/{signDate}'=>'get',
                                                'daily-signin/{groupId?}/{signDate?}'=>'get',
                                                'daily-signin/export/{groupId}/{signDate}'=>'get',
                                                'daily-signin/mail/{groupId}/{signDate}'=>'post',
                                    
                                                'worker-management'=>'get',
                                                'worker-management/add-worker'=>'post',
                                                'worker-management/get-worker-details/{authToken}'=>'get',
                                                'worker-management/edit-worker'=>'post',
                                                'worker-management/delete-worker'=>'post',
                                                'worker-management/disable-worker'=>'post',
                                                'worker-management/enable-worker'=>'post',
                                    
                                                'vehicle-management'=>'get',
                                                'vehicle-management/add-vehicle'=>'post',
                                                'vehicle-management/get-vehicle-details/{vehicleId}'=>'get',
                                                'vehicle-management/edit-vehicle'=>'post',
                                                'vehicle-management/delete-vehicle'=>'post',
                                                'vehicle-management/view/{vehicleId}/{inspectionId}'=>'get',
                                                'vehicle-management/view/{vehicleId}/{inspectionId?}'=>'get',
                                                'vehicle-management/export/{vehicleId}/{inspectionId}'=>'get',
                                                'vehicle-management/export/{vehicleId}/{inspectionId?}'=>'get',
                                                'vehicle-management/mail'=>'post',
                                                'vehicle-management/add-action'=>'post',
                                                'vehicle-management/get-inspection-details/{inspectionId}'=>'get',
                                                'vehicle-management/delete-vehicle'=>'post',
            
                                                'near-misses'=>'get',
                                                'near-misses/view/{nearMissId}'=>'get',
                                                'near-misses/export/{nearMissId}'=>'get',
                                                'near-misses/mail'=>'post',
                                                'near-misses/add-action'=>'post',
                                                'near-misses/delete-near-miss'=>'post',
                                                'near-misses/edit-near-miss'=>'post',
                                    
                                                'hazard-cards'=>'get',
                                                'hazard-cards/view/{hazardId}'=>'get',
                                                'hazard-cards/export/{hazardId}'=>'get',
                                                'hazard-cards/mail'=>'post',
                                                'hazard-cards/add-action'=>'post',
                                                'hazard-cards/delete-hazard-card'=>'post',
                                                'hazard-cards/edit-hazard-card'=>'post',
                                    
                                                'field-observations'=>'get',
                                                'field-observations/view/{positiveObservationId}'=>'get',
                                                'field-observations/export/{positiveObservationId}'=>'get',
                                                'field-observations/mail'=>'post',
                                                'field-observations/add-action'=>'post',
                                                'field-observations/delete-observation'=>'post',
                                                'field-observations/edit-observation'=>'post',
                                    
                                                'journeys'=>'get',
                                                'journey-management/view/{journeyId}'=>'get',
                                                'journey-management/view/{journeyId?}'=>'get',
                                                'journey-management/delete-journey'=>'post',
                                    
                                                'flha'=>'get',
                                                'flha/view/{flhaId}'=>'get',
                                                'flha/export/{flhaId}'=>'get',
                                                'flha/mail'=>'post',
                                                'flha/get-visitor-details/{visitorId}'=>'get',
                                                'flha/get-worker-details/{workerId}'=>'get',
                                                'flha/get-spotcheck-details/{spotcheckId}'=>'get',
                                                'flha/delete-flha'=>'post',
                                                'flha/edit-flha'=>'post',
                                    
                                                'faq'=>'get',
                                    
                                                'tailgates'=>'get',
                                                'tailgates/view/{tailgateId}'=>'get',
                                                'tailgates/export/{tailgateId}'=>'get',
                                                'tailgates/mail'=>'post',
                                                'tailgates/get-visitor-details/{visitorId}'=>'get',
                                                'tailgates/get-worker-details/{workerId}'=>'get',
                                                'tailgates/delete-tailgate'=>'post',
                                                'tailgates/edit-tailgate'=>'post',
                                    
                                                'incident-cards'=>'get',
                                                'incident-cards/view/{incidentId}'=>'get',
                                                'incident-cards/export/{incidentId}'=>'get',
                                                'incident-cards/get-person-details/{personId}'=>'get',
                                                'incident-cards/mail'=>'post',
                                                'incident-cards/add-action'=>'post',
                                                'incident-cards/delete-incident'=>'post',
                                                'incident-cards/edit-incident'=>'post',
                                    
                                                'cards/review' => 'post',
                                                'profile'      => 'post',
                                                'profile/disable-tutorial' => 'get',

                                                'tickets'=>'get',
                                                'tickets/create-ticket-view' => 'get',
                                                'tickets/view/{ticketId}'=>'get',
                                                'tickets/create' => 'post',
                                                'tickets/delete' => 'post',
                                                'tickets/mail'=>'post',
                                                'tickets/update'=>'post',
                                                'tickets/export/{ticketId}' => 'get',

                                                'safety-manual' => 'get',
                                                'safety-manual/revisions' => 'get',
                                                'safety-manual/section/{sectionid}' => 'get',
                                                'safety-manual/mail'=>'post',
                                                'safety-manual/edit-safety-manual' => 'post',
                                                '/safety-manual/upload-image' => 'post',
                                                'safety-manual/export/{sectionId?}/{subsectionId?}' => 'get',
                                                'safety-manual/mail/{sectionId?}/{subsectionId?}' => 'get'
                                          )           
                               ),
        UserRole::HEATH_ADMIN => array(
                                'name'=>'Health & safety account',
                                'routes'=>array(
                                                'admin-management'=>'get',
                                                'admin-management/add-admin'=>'post',
                                                'admin-management/edit-admin'=>'post',
                                                'admin-management/delete-admin'=>'post',
                                                'company-management'=>'get',
                                                'company-management/company-divisions'=>'post',
                                                'company-management/division-business-units'=>'post',
                                                'company-management/business-unit-groups'=>'post',
                                                'company-management/add-division'=>'post',
                                                'company-management/edit-division'=>'post',
                                                'company-management/delete-division'=>'post',
                                                'company-management/add-business-unit'=>'post',
                                                'company-management/edit-business-unit'=>'post',
                                                'company-management/delete-business-unit'=>'post',
                                                'company-management/add-group'=>'post',
                                                'company-management/edit-group'=>'post',
                                                'company-management/delete-group'=>'post',
                                                'company-management/add-helpline'=>'post',
                                                'company-management/delete-helpline'=>'post',
                                    
                                                'company-management/stats/{groupId}/{refDate}/{timeframe}'=>'get',
                                                'company-management/stats/{groupId?}/{refDate?}/{timeframe?}'=>'get',
                                                'company-management/stats/export/{groupId}/{refDate}/{timeframe}'=>'get',
                                                'company-management/stats/mail/{groupId}/{refDate}/{timeframe}'=>'post',
                                             
                                                'daily-signin/{groupId}/{signDate}'=>'get',
                                                'daily-signin/{groupId?}/{signDate?}'=>'get',
                                                'daily-signin/export/{groupId}/{signDate}'=>'get',
                                                'daily-signin/mail/{groupId}/{signDate}'=>'post',
                                                
                                                'upload-company-logo' => 'get|post',
                                                'company-logo' => 'get',
                                    
                                    
                                                'worker-management'=>'get',
                                                'worker-management/add-worker'=>'post',
                                                'worker-management/get-worker-details/{authToken}'=>'get',
                                                'worker-management/edit-worker'=>'post',
                                                'worker-management/delete-worker'=>'post',
                                                'worker-management/disable-worker'=>'post',
                                                'worker-management/enable-worker'=>'post',
                                    
                                                'vehicle-management'=>'get',
                                                'vehicle-management/add-vehicle'=>'post',
                                                'vehicle-management/get-vehicle-details/{vehicleId}'=>'get',
                                                'vehicle-management/edit-vehicle'=>'post',
                                                'vehicle-management/delete-vehicle'=>'post',
                                                'vehicle-management/view/{vehicleId}/{inspectionId}'=>'get',
                                                'vehicle-management/view/{vehicleId}/{inspectionId?}'=>'get',
                                                'vehicle-management/export/{vehicleId}/{inspectionId}'=>'get',
                                                'vehicle-management/export/{vehicleId}/{inspectionId?}'=>'get',
                                                'vehicle-management/mail'=>'post',
                                                'vehicle-management/add-action'=>'post',
                                                'vehicle-management/get-inspection-details/{inspectionId}'=>'get',
            
                                                'near-misses'=>'get',
                                                'near-misses/view/{nearMissId}'=>'get',
                                                'near-misses/export/{nearMissId}'=>'get',
                                                'near-misses/mail'=>'post',
                                                'near-misses/add-action'=>'post',
                                    
                                                'hazard-cards'=>'get',
                                                'hazard-cards/view/{hazardId}'=>'get',
                                                'hazard-cards/export/{hazardId}'=>'get',
                                                'hazard-cards/mail'=>'post',
                                                'hazard-cards/add-action'=>'post',
                                                
                                    
                                                'field-observations'=>'get',
                                                'field-observations/view/{positiveObservationId}'=>'get',
                                                'field-observations/export/{positiveObservationId}'=>'get',
                                                'field-observations/mail'=>'post',
                                                'field-observations/add-action'=>'post',
                                    
                                                'journeys'=>'get',
                                                'journey-management/view/{journeyId}'=>'get',
                                                'journey-management/view/{journeyId?}'=>'get',
                                    
                                                'flha'=>'get',
                                                'flha/view/{flhaId}'=>'get',
                                                'flha/export/{flhaId}'=>'get',
                                                'flha/mail'=>'post',
                                                'flha/get-visitor-details/{visitorId}'=>'get',
                                                'flha/get-worker-details/{workerId}'=>'get',
                                                'flha/get-spotcheck-details/{spotcheckId}'=>'get',
                                    
                                                'faq'=>'get',
                                                
                                                'tailgates'=>'get',
                                                'tailgates/view/{tailgateId}'=>'get',
                                                'tailgates/export/{tailgateId}'=>'get',
                                                'tailgates/mail'=>'post',
                                                'tailgates/get-visitor-details/{visitorId}'=>'get',
                                                'tailgates/get-worker-details/{workerId}'=>'get',
                                                
                                                'incident-cards'=>'get',
                                                'incident-cards/view/{incidentId}'=>'get',
                                                'incident-cards/export/{incidentId}'=>'get',
                                                'incident-cards/mail'=>'post',
                                                'incident-cards/add-action'=>'post',
                                    
                                                'cards/review' => 'post',
                                                'profile'      => 'post',
                                                'profile/disable-tutorial' => 'get',

                                                'tickets'=>'get',
                                                'tickets/create-ticket-view' => 'get',
                                                'tickets/view/{ticketId}'=>'get',
                                                'tickets/create' => 'post',
                                                'tickets/delete' => 'post',
                                                'tickets/mail'=>'post',
                                                'tickets/update'=>'post',
                                                'tickets/export/{ticketId}' => 'get',

                                                'safety-manual' => 'get',
                                                'safety-manual/revisions' => 'get',
                                                'safety-manual/section/{sectionid}' => 'get',
                                                'safety-manual/mail'=>'post',
                                                'safety-manual/edit-safety-manual' => 'post',
                                                '/safety-manual/upload-image' => 'post',
                                                'safety-manual/export/{sectionId?}/{subsectionId?}' => 'get',
                                                'safety-manual/mail/{sectionId?}/{subsectionId?}' => 'get'
                                    )
                               ),
        UserRole::ACCOUNT_ADMIN => array(
                                'name'=>'Account manager',
                                'routes'=>array(
                                                'admin-management'=>'get',
                                                'admin-management/add-admin'=>'post',
                                                'admin-management/edit-admin'=>'post',
                                                'admin-management/delete-admin'=>'post',
                                                'company-management'=>'get',
                                                'company-management/company-divisions'=>'post',
                                                'company-management/division-business-units'=>'post',
                                                'company-management/business-unit-groups'=>'post',
                                                'company-management/add-helpline'=>'post',
                                                'company-management/delete-helpline'=>'post',
                                                'upload-company-logo' => 'get|post',
                                                'company-logo' => 'get',
                                    
                                                'company-management/stats/{groupId}/{refDate}/{timeframe}'=>'get',
                                                'company-management/stats/{groupId?}/{refDate?}/{timeframe?}'=>'get',
                                                'company-management/stats/export/{groupId}/{refDate}/{timeframe}'=>'get',
                                                'company-management/stats/mail/{groupId}/{refDate}/{timeframe}'=>'post',
                                    
                                                'daily-signin/{groupId}/{signDate}'=>'get',
                                                'daily-signin/{groupId?}/{signDate?}'=>'get',
                                                'daily-signin/export/{groupId}/{signDate}'=>'get',
                                                'daily-signin/mail/{groupId}/{signDate}'=>'post',
                                                
                                                'worker-management'=>'get',
                                                'worker-management/add-worker'=>'post',
                                                'worker-management/get-worker-details/{authToken}'=>'get',
                                                'worker-management/edit-worker'=>'post',
                                                'worker-management/delete-worker'=>'post',
                                                'worker-management/disable-worker'=>'post',
                                                'worker-management/enable-worker'=>'post',
                                    
                                                'vehicle-management'=>'get',
                                                'vehicle-management/add-vehicle'=>'post',
                                                'vehicle-management/get-vehicle-details/{vehicleId}'=>'get',
                                                'vehicle-management/edit-vehicle'=>'post',
                                                'vehicle-management/delete-vehicle'=>'post',
                                                'vehicle-management/view/{vehicleId}/{inspectionId}'=>'get',
                                                'vehicle-management/view/{vehicleId}/{inspectionId?}'=>'get',
                                                'vehicle-management/export/{vehicleId}/{inspectionId}'=>'get',
                                                'vehicle-management/export/{vehicleId}/{inspectionId?}'=>'get',
                                                'vehicle-management/mail'=>'post',
                                                'vehicle-management/add-action'=>'post',
                                                'vehicle-management/get-inspection-details/{inspectionId}'=>'get',
            
                                                
                                                'near-misses'=>'get',
                                                'near-misses/view/{nearMissId}'=>'get',
                                                'near-misses/export/{nearMissId}'=>'get',
                                                'near-misses/mail'=>'post',
                                                'near-misses/add-action'=>'post',
                                    
                                                'hazard-cards'=>'get',
                                                'hazard-cards/view/{hazardId}'=>'get',
                                                'hazard-cards/export/{hazardId}'=>'get',
                                                'hazard-cards/mail'=>'post',
                                                'hazard-cards/add-action'=>'post',
                                    
                                    
                                                'field-observations'=>'get',
                                                'field-observations/view/{positiveObservationId}'=>'get',
                                                'field-observations/export/{positiveObservationId}'=>'get',
                                                'field-observations/mail'=>'post',
                                                'field-observations/add-action'=>'post',
                                    
                                                'journeys'=>'get',
                                                'journey-management/view/{journeyId}'=>'get',
                                                'journey-management/view/{journeyId?}'=>'get',
                                    
                                                'flha'=>'get',
                                                'flha/view/{flhaId}'=>'get',
                                                'flha/export/{flhaId}'=>'get',
                                                'flha/mail'=>'post',
                                                'flha/get-visitor-details/{visitorId}'=>'get',
                                                'flha/get-worker-details/{workerId}'=>'get',
                                                'flha/get-spotcheck-details/{spotcheckId}'=>'get',
                                    
                                                'faq'=>'get',
                                                
                                                'tailgates'=>'get',
                                                'tailgates/view/{tailgateId}'=>'get',
                                                'tailgates/export/{tailgateId}'=>'get',
                                                'tailgates/mail'=>'post',
                                                'tailgates/get-visitor-details/{visitorId}'=>'get',
                                                'tailgates/get-worker-details/{workerId}'=>'get',
                                    
                                                'incident-cards'=>'get',
                                                'incident-cards/view/{incidentId}'=>'get',
                                                'incident-cards/export/{incidentId}'=>'get',
                                                'incident-cards/mail'=>'post',
                                                'incident-cards/add-action'=>'post',
                                    
                                                'cards/review' => 'post',
                                                'profile'      => 'post',
                                                'profile/disable-tutorial' => 'get',
                               ),
            )
            
);

?>
