    // This identifies your website in the createToken call below
    // The meta information of the publishable key is generated by the server on the credit-card-details.blade.php page which is sourced from the single all powerful stripe config file
    var stripeKey = $('meta[name="publishable-key"]').attr('content');
    Stripe.setPublishableKey(stripeKey);
    
    $(document).ready(function(){
        
        $("#credit-card-input").payment('formatCardNumber');

        $("#payment-form").submit(function(e) {
            var self = this;
            var $form = $(self);
            $form.find('button').html('Sending... <img src="' + site + 'assets/img/loading.gif" alt="." style="width:15px; height:15px; margin-top:-4px;"></img>');
            // Disable the submit button to prevent repeated clicks
            $form.find('button').prop('disabled', true);

            // Check the coupon before submitting
            if($('#checkableCouponCode').val()){
                // Having these style items here ensures that if the user clicks SEND with no emails, the button doesn't change
                $.get(site+'billing/check-coupon/' + $('#checkableCouponCode').val(), function(response){
                    if(response.status){
                        // Coupon is good -- proceed with submit.
                        Stripe.card.createToken($form, stripeResponseHandler);
                    } else {
                        $.alert({
                            title: 'Invalid Coupon!',
                            content: 'You entered an invalid coupon.',
                            confirmButtonClass: 'btn-primary',
                            onClose: function(){
                              $form.find('button').html('Submit Credit Card Details');
                              $form.find('button').prop('disabled', false);
                            }
                        });
                   }
                },'json');
            } else {
                // No coupon submitted --  proceed with submit
                Stripe.card.createToken($form, stripeResponseHandler);
            }

            return false; //is superfluous, but I put it here as a fallback
        });

        function stripeResponseHandler(status, response) {
            var $form = $('#payment-form');

            if (response.error) {
              $.alert({
                  title: 'Error!',
                  content: response.error.message,
                  confirmButtonClass: 'btn-primary',
                  confirm: function(){
                    //
                  }
              });

              $form.find('button').html('Submit Credit Card Details');
              $form.find('button').prop('disabled', false);
            } else {
              // response contains id and card, which contains additional card details
              var token = response.id;
              // Insert the token into the form so it gets submitted to the server
              $form.append($('<input type="hidden" name="stripeToken" />').val(token));
              // and submit
              $form.get(0).submit();
            }
        };    

    });

